### PR TITLE
update node-webkit-builder dependency to support nwjs.

### PR DESCRIPTION
**Pull request by hugoruscitti**

### CODE REVIEW

**Comment by adam-lynch** [comment]
Thanks

**Comment by steffenmllr** [comment]
shouldn't semver take care of that? `1.0.0` => `1.0.x`

**Comment by adam-lynch** [comment]
I'm assuming it's because there's an important change in 1.0.6 to do with the download URLs or something like that, so no one out there should have the latest grunt-node-webkit-builder with a version of node-webkit-builder (as a dependency) which is less than 1.0.6.

**Comment by ashishpai1** [comment]
Hi Adam, 

I am using node-webkit version 0.11.0 , grunt-node-webkit-builder@0.2.3 and node-webkit-builder@0.2.0(which is a dependency to grunt-node-webkit-builder) but when I try to build the package for mac i am getting the same error. 

Create cache folder in /Users/apai/Pictures/NodeCode/cache/0.11.0-rc1
Downloading: http://dl.node-webkit.org/v0.11.0-rc1/node-webkit-v0.11.0-rc1-osx-ia32.zip
undefined
Fatal error: Unable to download nodewebkit. 

Do i need to change my package from node-webkit-builder to nw-builder? 

Thanks,
Ashish

**Comment by adam-lynch** [comment]
@ashishpai1 Either that or try specifying a version when building.

**Pull request merged**
